CAT_FEATURES = ["CITY"]

NUM_FEATURES = ["SM_ROOTZONE","SM_SURFACE","PRECIPTOTCORR",
            "T2M","T2M_MAX","T2M_MIN","QV2M","RH2M","WS10M","PS",
            "PRECTOTCORR_1d", "PRECTOTCORR_3d", "PRECTOTCORR_7d", "PRECTOTCORR_14d"
            "SM_ROOTZONE_3d_MEAN", "SM_SURFACE_3d_MEAN", "SM_ROOTZONE_7d_MEAN",
            "SM_SURFACE_7d_MEAN", "FLOOD_IN_LAST_30d", "PRECTOTCORR_1d_CHANGE",
            "SM_ROOTZONE_1d_CHANGE", "SM_SURFACE_1d_CHANGE", "DOFY_SINE", "DOFY_COSINE"]

TARGET_FEATURE = ["FLOOD_TOMORROW"]
